# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A guide to Indians in usa
email: visablog.pk.ravi.fall.2016@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lonely Indians is a how to guide for immigrants to survive in USA.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lonelyindians.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: 

# Comments
disqus-shortname: 

#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda

#facebook like box
fb-app-id: 
fb-page-url: 
fb-page-title: 

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

